import { useEffect, useMemo, useState } from "react";
import { ClipboardList, Edit2, Plus, Trash2, X } from "lucide-react";
import { api } from "../services/api";
import { toast } from "../utils/toast";

const emptyCategory = { kode_kategori: "", nama_kategori: "", jenis_mode: "REQUIRED", urutan: 0, is_active: "Y" };
const emptyType = { id_kategori_lembur: "", kode_jenis: "", nama_jenis: "", kode_perilaku: "REGULAR", requires_replacement_officer: "N", evidence_optional: "N", max_daily_hours: 4, urutan: 0, is_active: "Y" };

export const MasterLemburPage = () => {
  const [categories, setCategories] = useState([]); const [query, setQuery] = useState(""); const [dialog, setDialog] = useState(null); const [form, setForm] = useState({}); const [saving, setSaving] = useState(false);
  const load = async () => { try { const response = await api.client.get("/master-lembur"); setCategories(response.data?.data || []); } catch (error) { toast.error(error.response?.data?.message || "Gagal memuat Master Lembur."); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => categories.filter((category) => `${category.kode_kategori} ${category.nama_kategori} ${(category.jenisPekerjaan || []).map((item) => `${item.kode_jenis} ${item.nama_jenis}`).join(" ")}`.toLowerCase().includes(query.toLowerCase())), [categories, query]);
  const openCategory = (item = null) => { setDialog({ kind: "category", item }); setForm(item ? { ...item } : { ...emptyCategory }); };
  const openType = (category, item = null) => { setDialog({ kind: "type", item }); setForm(item ? { ...item } : { ...emptyType, id_kategori_lembur: category.id_kategori_lembur }); };
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const isCategory = dialog.kind === "category"; const id = isCategory ? dialog.item?.id_kategori_lembur : dialog.item?.id_jenis_pekerjaan_lembur; const base = isCategory ? "/master-lembur/categories" : "/master-lembur/types"; if (id) await api.client.put(`${base}/${id}`, form); else await api.client.post(base, form); toast.success("Master lembur berhasil disimpan."); setDialog(null); await load(); } catch (error) { toast.error(error.response?.data?.message || "Gagal menyimpan Master Lembur."); } finally { setSaving(false); } };
  const remove = async (kind, id) => { if (!window.confirm("Hapus data master ini? Data yang sudah digunakan sebaiknya dinonaktifkan.")) return; try { await api.client.delete(`/master-lembur/${kind === "category" ? "categories" : "types"}/${id}`); toast.success("Data master berhasil dihapus."); await load(); } catch (error) { toast.error(error.response?.data?.message || "Data tidak dapat dihapus."); } };
  return <div className="p-3 sm:p-6 space-y-5"><div className="flex flex-col sm:flex-row gap-3 justify-between sm:items-end"><div><h1 className="text-xl font-black flex items-center gap-2"><ClipboardList className="w-6 h-6 text-indigo-600" />Master Kategori &amp; Jenis Lembur</h1><p className="text-xs text-slate-500 mt-1">Kelola struktur kategori dan jenis pekerjaan yang digunakan pada SPKL dan transaksi Lembur.</p></div><button onClick={() => openCategory()} className="h-10 px-4 rounded-xl bg-indigo-600 text-white font-black text-xs inline-flex items-center gap-2"><Plus className="w-4 h-4" />Tambah Kategori</button></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari kategori atau jenis pekerjaan..." className="form-input max-w-md" />
  <div className="space-y-3">{visible.map((category) => <section key={category.id_kategori_lembur} className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><header className="p-4 bg-slate-50 flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-mono text-xs font-black text-indigo-700">{category.kode_kategori}</span><span className={`px-2 py-0.5 rounded-full text-[10px] font-black ${category.is_active === "Y" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{category.is_active === "Y" ? "AKTIF" : "NONAKTIF"}</span></div><h2 className="font-black text-slate-900 mt-1">{category.nama_kategori}</h2><p className="text-[11px] text-slate-500">Mode jenis: <b>{category.jenis_mode}</b></p></div><div className="flex gap-2"><button onClick={() => openCategory(category)} className="w-9 h-9 rounded-lg bg-indigo-50 text-indigo-600 inline-flex items-center justify-center"><Edit2 className="w-4 h-4" /></button><button onClick={() => remove("category", category.id_kategori_lembur)} className="w-9 h-9 rounded-lg bg-rose-50 text-rose-600 inline-flex items-center justify-center"><Trash2 className="w-4 h-4" /></button>{category.jenis_mode !== "NONE" && <button onClick={() => openType(category)} className="h-9 px-3 rounded-lg bg-emerald-600 text-white font-black text-[11px] inline-flex items-center gap-1"><Plus className="w-3.5 h-3.5" />Jenis</button>}</div></header><div className="divide-y divide-slate-100">{(category.jenisPekerjaan || []).length ? category.jenisPekerjaan.map((item) => <div key={item.id_jenis_pekerjaan_lembur} className="p-3.5 flex justify-between gap-3 items-center"><div><p className="text-xs font-black text-slate-800">{item.nama_jenis}</p><p className="text-[10px] text-slate-500 font-mono">{item.kode_jenis} · {item.kode_perilaku} · maks. {item.max_daily_hours} jam</p></div><div className="flex gap-1"><button onClick={() => openType(category, item)} className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-600 inline-flex items-center justify-center"><Edit2 className="w-3.5 h-3.5" /></button><button onClick={() => remove("type", item.id_jenis_pekerjaan_lembur)} className="w-8 h-8 rounded-lg bg-rose-50 text-rose-600 inline-flex items-center justify-center"><Trash2 className="w-3.5 h-3.5" /></button></div></div>) : <p className="p-4 text-xs text-slate-400 italic">Kategori ini tidak memiliki jenis pekerjaan.</p>}</div></section>)}</div>
  {dialog && <div className="fixed inset-0 z-50 bg-slate-950/60 flex items-center justify-center p-4"><form onSubmit={save} className="bg-white rounded-2xl shadow-2xl w-full max-w-xl p-5 space-y-4"><div className="flex justify-between"><h2 className="font-black">{dialog.item ? "Edit" : "Tambah"} {dialog.kind === "category" ? "Kategori" : "Jenis Pekerjaan"}</h2><button type="button" onClick={() => setDialog(null)}><X className="w-5 h-5" /></button></div>{dialog.kind === "category" ? <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold">Kode<input required value={form.kode_kategori} onChange={(e) => setForm({ ...form, kode_kategori: e.target.value.toUpperCase() })} className="form-input mt-1" /></label><label className="text-xs font-bold">Nama<input required value={form.nama_kategori} onChange={(e) => setForm({ ...form, nama_kategori: e.target.value })} className="form-input mt-1" /></label><label className="text-xs font-bold">Mode Jenis<select value={form.jenis_mode} onChange={(e) => setForm({ ...form, jenis_mode: e.target.value })} className="form-input mt-1"><option>NONE</option><option>OPTIONAL</option><option>REQUIRED</option></select></label><StatusFields form={form} setForm={setForm} /></div> : <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold">Kode<input required value={form.kode_jenis} onChange={(e) => setForm({ ...form, kode_jenis: e.target.value.toUpperCase() })} className="form-input mt-1" /></label><label className="text-xs font-bold">Nama<input required value={form.nama_jenis} onChange={(e) => setForm({ ...form, nama_jenis: e.target.value })} className="form-input mt-1" /></label><label className="text-xs font-bold">Perilaku<select value={form.kode_perilaku} onChange={(e) => setForm({ ...form, kode_perilaku: e.target.value })} className="form-input mt-1"><option>REGULAR</option><option>SIAGA_HARI_LIBUR</option><option>PENGGANTI_KETIDAKHADIRAN</option></select></label><label className="text-xs font-bold">Maks. Jam/Hari<input type="number" min="1" max="24" value={form.max_daily_hours} onChange={(e) => setForm({ ...form, max_daily_hours: Number(e.target.value) })} className="form-input mt-1" /></label><StatusFields form={form} setForm={setForm} /></div>}<div className="flex justify-end gap-2"><button type="button" onClick={() => setDialog(null)} className="h-10 px-4 rounded-xl bg-slate-100 font-bold text-xs">Batal</button><button disabled={saving} className="h-10 px-5 rounded-xl bg-indigo-600 text-white font-black text-xs">{saving ? "Menyimpan..." : "Simpan"}</button></div></form></div>}</div>;
};
const StatusFields = ({ form, setForm }) => <><label className="text-xs font-bold">Urutan<input type="number" min="0" value={form.urutan} onChange={(e) => setForm({ ...form, urutan: Number(e.target.value) })} className="form-input mt-1" /></label><label className="text-xs font-bold">Status<select value={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.value })} className="form-input mt-1"><option value="Y">Aktif</option><option value="N">Nonaktif</option></select></label></>;
