import { useEffect, useMemo, useState } from "react";
import { ClipboardList, Edit2, Eye, Plus, Search, Trash2, X } from "lucide-react";
import { api } from "../services/api";
import { toast } from "../utils/toast";
import { formatDateIndonesian } from "../utils/formatters";

const emptyForm = { id_unit: "", tgl_lembur: "", kategori_lembur: "", jenis_pekerjaan: "", kode_jenis_pekerjaan: "REGULAR", area_group: "", detail_pekerjaan: "", status_spkl: "ACTIVE", id_petugas: [] };

export const PerintahKerjaLemburPage = ({ currentUser, navbarScope, startDate, endDate }) => {
  const canWrite = ["checker", "admin", "superadmin"].includes(currentUser?.role);
  const [rows, setRows] = useState([]); const [officers, setOfficers] = useState([]); const [holidays, setHolidays] = useState([]);
  const [query, setQuery] = useState(""); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [viewing, setViewing] = useState(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const allowedIds = navbarScope?.activeFilterUnitIds || navbarScope?.allowedUnitIds || [];
  const units = (navbarScope?.selectableUnits || []).filter((unit) => !allowedIds.length || allowedIds.includes(Number(unit.id_unit)));
  const load = async () => { try { const [spkl, petugas, hari] = await Promise.all([api.getSpkl({ tgl_awal: startDate, tgl_akhir: endDate }), api.getPetugas(), api.client.get("/hari-libur", { params: { limit: 1000 } })]); setRows(spkl); setOfficers(petugas); setHolidays(hari.data?.data || []); } catch (e) { toast.error(e.response?.data?.message || "Gagal memuat data SPKL."); } };
  useEffect(() => { load(); }, [startDate, endDate]);
  const visible = useMemo(() => rows.filter((row) => (!allowedIds.length || allowedIds.includes(Number(row.id_unit))) && (!query || `${row.nomor_dokumen} ${row.kategori_lembur} ${row.jenis_pekerjaan}`.toLowerCase().includes(query.toLowerCase()))), [rows, query, allowedIds.join(",")]);
  const availableOfficers = officers.filter((item) => String(item.id_unit) === String(form.id_unit) && item.is_active !== "N");
  const startAdd = () => { setEditing(null); setForm({ ...emptyForm, id_unit: units.length === 1 ? String(units[0].id_unit) : "" }); setOpen(true); };
  const startEdit = (row) => { setEditing(row); setForm({ id_unit: String(row.id_unit), tgl_lembur: row.tgl_lembur, kategori_lembur: row.kategori_lembur, jenis_pekerjaan: row.jenis_pekerjaan, kode_jenis_pekerjaan: row.kode_jenis_pekerjaan, area_group: row.area_group || "", detail_pekerjaan: row.detail_pekerjaan || "", status_spkl: row.status_spkl, id_petugas: row.assignments.map((a) => Number(a.id_petugas)) }); setOpen(true); };
  const toggleOfficer = (id) => setForm((current) => ({ ...current, id_petugas: current.id_petugas.includes(id) ? current.id_petugas.filter((value) => value !== id) : [...current.id_petugas, id] }));
  const save = async (event) => { event.preventDefault(); if (!form.id_petugas.length) return toast.error("Pilih minimal satu petugas."); if (form.kode_jenis_pekerjaan === "SIAGA_HARI_LIBUR" && !holidays.some((h) => h.is_active === "Y" && h.tanggal === form.tgl_lembur)) return toast.error("Tanggal Siaga tidak terdaftar pada Master Hari Libur aktif."); setSaving(true); try { const payload = { ...form, id_unit: Number(form.id_unit) }; if (editing) await api.updateSpkl(editing.id_spkl, payload); else await api.createSpkl(payload); setOpen(false); await load(); toast.success(`SPKL berhasil ${editing ? "diperbarui" : "dibuat"}.`); } catch (e) { toast.error(e.response?.data?.message || "Gagal menyimpan SPKL."); } finally { setSaving(false); } };
  const remove = async (row) => { if (!confirm(`Hapus ${row.nomor_dokumen}?`)) return; try { await api.deleteSpkl(row.id_spkl); await load(); toast.success("SPKL berhasil dihapus."); } catch (e) { toast.error(e.response?.data?.message || "Gagal menghapus SPKL."); } };
  return <div className="p-3 sm:p-6 space-y-5">
    <div className="flex flex-col sm:flex-row justify-between gap-3"><div><h1 className="text-xl font-black text-slate-900 flex items-center gap-2"><ClipboardList className="text-indigo-600" /> Surat Perintah Kerja Lembur</h1><p className="text-xs text-slate-500">SPKL pada scope Unit Role dan filter Navbar aktif.</p></div>{canWrite && <button onClick={startAdd} className="px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-bold flex gap-2 items-center"><Plus size={16}/> Buat SPKL</button>}</div>
    <div className="relative max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari nomor, kategori, atau pekerjaan" className="w-full h-10 pl-9 pr-3 border rounded-xl text-xs"/></div>
    <div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3 text-left">Nomor SPKL</th><th className="p-3 text-left">Tanggal</th><th className="p-3 text-left">Unit</th><th className="p-3 text-left">Pekerjaan</th><th className="p-3 text-center">Realisasi</th><th className="p-3 text-center">Status</th><th className="p-3 text-center">Aksi</th></tr></thead><tbody>{visible.map((row)=><tr key={row.id_spkl} className="border-t"><td className="p-3 font-bold">{row.nomor_dokumen}</td><td className="p-3">{formatDateIndonesian(row.tgl_lembur)}</td><td className="p-3">{row.unit?.nama_unit}</td><td className="p-3"><b>{row.kategori_lembur}</b><br/><span className="text-slate-500">{row.jenis_pekerjaan}</span></td><td className="p-3 text-center">{row.assignments?.filter((a)=>a.lembur).length || 0}/{row.assignments?.length || 0}</td><td className="p-3 text-center"><span className="px-2 py-1 bg-indigo-50 text-indigo-700 rounded-lg font-bold">{row.status_spkl}</span></td><td className="p-3"><div className="flex justify-center gap-1"><button onClick={()=>setViewing(row)} className="p-2"><Eye size={15}/></button>{canWrite && <><button onClick={()=>startEdit(row)} className="p-2 text-indigo-600"><Edit2 size={15}/></button><button onClick={()=>remove(row)} className="p-2 text-rose-600"><Trash2 size={15}/></button></>}</div></td></tr>)}{!visible.length&&<tr><td colSpan="7" className="p-10 text-center text-slate-400">Belum ada SPKL pada filter aktif.</td></tr>}</tbody></table></div>
    {(open || viewing) && <div className="fixed inset-0 z-50 bg-slate-950/60 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-5 w-full max-w-3xl max-h-[90vh] overflow-y-auto"><div className="flex justify-between mb-4"><h2 className="font-black">{viewing ? "Detail SPKL" : editing ? "Edit SPKL" : "Buat SPKL"}</h2><button onClick={()=>{setOpen(false);setViewing(null)}}><X/></button></div>{viewing ? <div className="grid sm:grid-cols-2 gap-3 text-xs">{[["Nomor",viewing.nomor_dokumen],["Tanggal",formatDateIndonesian(viewing.tgl_lembur)],["Kategori",viewing.kategori_lembur],["Pekerjaan",viewing.jenis_pekerjaan],["Unit",viewing.unit?.nama_unit],["Petugas",viewing.assignments?.map((a)=>a.petugas?.nama).join(", ")]].map(([l,v])=><div key={l} className="p-3 bg-slate-50 rounded-xl"><span className="text-slate-400">{l}</span><p className="font-bold mt-1">{v||"-"}</p></div>)}</div> : <form onSubmit={save} className="space-y-4 text-xs"><div className="grid sm:grid-cols-2 gap-3"><label>Unit<select required value={form.id_unit} onChange={(e)=>setForm({...form,id_unit:e.target.value,id_petugas:[]})} className="form-input mt-1"><option value="">Pilih unit</option>{units.map((u)=><option key={u.id_unit} value={u.id_unit}>{u.nama_unit}</option>)}</select></label><label>Tanggal<input required type="date" value={form.tgl_lembur} onChange={(e)=>setForm({...form,tgl_lembur:e.target.value})} className="form-input mt-1"/></label><label>Kategori<input required value={form.kategori_lembur} onChange={(e)=>setForm({...form,kategori_lembur:e.target.value})} className="form-input mt-1"/></label><label>Jenis pekerjaan<input required value={form.jenis_pekerjaan} onChange={(e)=>setForm({...form,jenis_pekerjaan:e.target.value})} className="form-input mt-1"/></label><label>Tipe pekerjaan<select value={form.kode_jenis_pekerjaan} onChange={(e)=>setForm({...form,kode_jenis_pekerjaan:e.target.value})} className="form-input mt-1"><option value="REGULAR">Reguler</option><option value="SIAGA_HARI_LIBUR">Siaga Hari Libur</option></select></label><label>Area/Group<input value={form.area_group} onChange={(e)=>setForm({...form,area_group:e.target.value})} className="form-input mt-1"/></label></div><label>Detail<textarea value={form.detail_pekerjaan} onChange={(e)=>setForm({...form,detail_pekerjaan:e.target.value})} className="form-input mt-1 min-h-20"/></label><div><p className="font-bold mb-2">Petugas</p><div className="grid sm:grid-cols-2 gap-2 max-h-48 overflow-y-auto">{availableOfficers.map((p)=><label key={p.id_petugas} className="p-3 border rounded-xl flex gap-2"><input type="checkbox" checked={form.id_petugas.includes(Number(p.id_petugas))} onChange={()=>toggleOfficer(Number(p.id_petugas))}/><span><b>{p.nama}</b><br/>{p.nip}</span></label>)}</div></div><div className="flex justify-end"><button disabled={saving} className="px-5 py-2.5 bg-indigo-600 text-white rounded-xl font-bold">{saving?"Menyimpan...":"Simpan SPKL"}</button></div></form>}</div></div>}
  </div>;
};
