export const INITIAL_USERS = [
  {
    id: "usr-0",
    id_user: 1,
    nip: "SA-001",
    username: "superadmin",
    name: "Super Admin System",
    email: "superadmin@pln.co.id",
    role: "superadmin",
    password: "password123",
    jabatan: "Administrator Utama System",
    unitUpt: "UPT Semarang",
    unitUltg: "ULTG Semarang",
    garduInduk: "GI Krapyak",
    tglLahir: "1988-01-01",
    tanggalMasuk: "2020-01-01",
    gajiPokok: 1e7,
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "usr-1",
    id_user: 2,
    nip: "8912345Z",
    username: "maker",
    name: "Budi Santoso (Maker)",
    email: "budi.santoso@pln.co.id",
    role: "maker",
    password: "password123",
    jabatan: "Teknisi Pemeliharaan GI",
    unitUpt: "UPT Semarang",
    unitUltg: "ULTG Semarang",
    garduInduk: "GI Krapyak",
    tglLahir: "1998-03-15",
    tanggalMasuk: "2022-03-15",
    gajiPokok: 55e5,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "usr-2",
    id_user: 3,
    nip: "8534567X",
    username: "checker",
    name: "Ahmad Dani (Checker)",
    email: "ahmad.dani@pln.co.id",
    role: "checker",
    password: "password123",
    jabatan: "Team Leader (TL) PLN Pemeliharaan GI",
    unitUpt: "UPT Semarang",
    unitUltg: "ULTG Semarang",
    garduInduk: "GI Krapyak",
    tglLahir: "1993-01-10",
    tanggalMasuk: "2018-01-10",
    gajiPokok: 85e5,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "usr-3",
    id_user: 4,
    nip: "7823411V",
    username: "approval1",
    name: "Ir. Bambang Suto (Approval 1)",
    email: "bambang.suto@pln.co.id",
    role: "approved1",
    password: "password123",
    jabatan: "Manager (MAN) UPT PLN JATENG DIY",
    unitUpt: "UPT Semarang",
    unitUltg: "ULTG Semarang",
    garduInduk: "GI Krapyak",
    tglLahir: "1985-02-14",
    tanggalMasuk: "2010-02-14",
    gajiPokok: 18e6,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "usr-4",
    id_user: 5,
    nip: "9112345W",
    username: "approval2",
    name: "Andi Prasetyo (Approval 2)",
    email: "andi.prasetyo@pln-es.co.id",
    role: "approved2",
    password: "password123",
    jabatan: "Team Leader (TL) Electricity Services",
    unitUpt: "UPT Semarang",
    unitUltg: "ULTG Salatiga",
    garduInduk: "GI Ungaran",
    tglLahir: "1994-11-01",
    tanggalMasuk: "2019-11-01",
    gajiPokok: 8e6,
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "usr-5",
    id_user: 6,
    nip: "8876543A",
    username: "approval3",
    name: "Hendra Wijaya (Approval 3)",
    email: "hendra.wijaya@pln-es.co.id",
    role: "approved3",
    password: "password123",
    jabatan: "Assistant Manager (AMN) Electricity Services",
    unitUpt: "UPT Semarang",
    unitUltg: "ULTG Semarang",
    garduInduk: "GI Tuntang",
    tglLahir: "1991-04-12",
    tanggalMasuk: "2016-04-12",
    gajiPokok: 135e5,
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80"
  }
];
export const INITIAL_SETTINGS = {
  maxCutiTahunanPerTahun: 12,
  maxIjinTahunan: 6,
  overtimeFormula: {
    multiplierFirstHour: 1.5,
    multiplierSubsequentHours: 2,
    holidayMultiplier: 2,
    maxHoursPerDay: 4,
    maxHoursPerMonth: 56,
    divisorMonthlySalary: 173
  },
  uptList: ["UPT Semarang", "UPT Purwokerto", "UPT Surakarta"],
  ultgList: ["ULTG Semarang", "ULTG Salatiga", "ULTG Kudus", "ULTG Purwokerto"],
  giList: ["GI Krapyak", "GI Ungaran", "GI Tuntang", "GI Kalisari", "GI Tambakakrik"]
};
export const INITIAL_SUBMISSIONS = [];
export const INITIAL_NOTIFICATIONS = [];
export const INITIAL_ATTENDANCE = [
  { id: "att-1", employeeNip: "8912345Z", employeeName: "Budi Santoso", unit: "GI Krapyak", tanggal: "2026-07-21", jamMasuk: "07:25", jamKeluar: "16:05", status: "Hadir", lokasiCheckin: "GI Krapyak GPS OK" },
  { id: "att-2", employeeNip: "9023456Y", employeeName: "Siti Aminah", unit: "ULTG Semarang", tanggal: "2026-07-21", jamMasuk: "-", jamKeluar: "-", status: "Cuti", lokasiCheckin: "-" },
  { id: "att-3", employeeNip: "8534567X", employeeName: "Ahmad Dani", unit: "GI Ungaran", tanggal: "2026-07-21", jamMasuk: "07:15", jamKeluar: "-", status: "Hadir", lokasiCheckin: "GI Ungaran GPS OK" },
  { id: "att-4", employeeNip: "9112345W", employeeName: "Andi Prasetyo", unit: "ULTG Salatiga", tanggal: "2026-07-21", jamMasuk: "-", jamKeluar: "-", status: "Ijin", lokasiCheckin: "-" },
  { id: "att-5", employeeNip: "8876543A", employeeName: "Hendra Wijaya", unit: "GI Tuntang", tanggal: "2026-07-21", jamMasuk: "-", jamKeluar: "-", status: "SPPD", lokasiCheckin: "Salatiga Tower Field" }
];
